### ISSUE TITLE
what if src_embedding_dim and tgt_embedding_dim is different

### ISSUE THREAD

**Issue by gardenia22** [tnq177/improving_lexical_choice_in_nmt#1]
@tnq177 just wondering what if the src_embedding_dim and tgt_embedding_dim is different. For the implementation fixnorm+lex, in model.py 153 line:

`lexicons = lex_hider.transform(lex_inputs) + lex_inputs`

And If I understand correctly, this should be in corresponding with the following equation in your paper:
![image](https://user-images.githubusercontent.com/3919482/43368468-5e050666-9312-11e8-9d5d-c11170bcb68c.png)

Here the output of lex_hider(i.e., `tanh(W*f_t^l)`) should be in dimension of tgt_embedding_dim, but the lex_inputs(i.e., `f_t^l`) is still in the dimension of src_embedding_dim, how to add the two matrix with different dimensions?

**Comment by tnq177** [comment]
hi @gardenia22 , when I first implemented NMT, I wanted it to be more general to different settings so I wrote the code as if we could set src_embedding_dim != trg_embedding_dim. However, as more experiments I do, as I notice there's no need for that. So in fact in my later code, I always kept in mind that all hidden vectors actually have the same dim. Sorry for the confusion. 

If you want you can always use different dims for src and target embedding and ignore the skip connection. In later experiments I actually found skip connections unnecessary.

**Comment by gardenia22** [comment]
@tnq177 thanks for your clarification. Can you share more details about the skip connections? Does it mean to remove the hidden layer completely or keep the lex_hider but removing the latter term so the hidden layer becomes:

![image](https://user-images.githubusercontent.com/3919482/43368752-23f6d774-9317-11e8-8412-47afde69ae8c.png)

**Comment by tnq177** [comment]
@gardenia22 yup that equation is correct, still need the hidden layer.
